
project_id = "aqqbxivolegafwuurxxm"

[functions.market-data]
verify_jwt = false

[functions.market-headlines]
verify_jwt = false

[functions.marketstack-data]
verify_jwt = false

[functions.fred-data]
verify_jwt = false

[functions.securities-search]
verify_jwt = false

[functions.enhanced-market-data]
verify_jwt = false

[functions.scheduled-market-refresh]
verify_jwt = false

[functions.polygon-market-movers]
verify_jwt = false

[functions.fmp-market-data]
verify_jwt = false
